//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0
{
    public partial class Certificate
    {
        protected global::System.Web.UI.WebControls.Label lblStudentName;
        protected global::System.Web.UI.WebControls.Label lblCourseTitle;
        protected global::System.Web.UI.WebControls.Label lblIssueDate;
        protected global::System.Web.UI.WebControls.Label lblCertificateId;
    }
}
