//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl masterBody;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
