//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0
{
    public partial class TakeQuiz
    {
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBackCourse;
        protected global::System.Web.UI.WebControls.Label lblCourseName;
        protected global::System.Web.UI.WebControls.Label lblQuizTitle;
        protected global::System.Web.UI.WebControls.Label lblQuizDescription;
        protected global::System.Web.UI.WebControls.Label lblPassingRequirement;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divResultIcon;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl hResultHeading;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pResultSub;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkRetake;
        protected global::System.Web.UI.WebControls.Panel pnlQuizForm;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.Button btnSubmitQuiz;
    }
}
