//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0
{
    public partial class ViewLesson
    {
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBack;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divProgressFill;
        protected global::System.Web.UI.WebControls.Label lblCourseProgressPct;
        protected global::System.Web.UI.WebControls.Label lblOrder;
        protected global::System.Web.UI.WebControls.Label lblOrderSubtitle;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Panel pnlBadgeCompleted;
        protected global::System.Web.UI.WebControls.Panel pnlBadgeIncomplete;
        protected global::System.Web.UI.WebControls.Panel pnlVideo;
        protected global::System.Web.UI.HtmlControls.HtmlIframe videoFrame;
        protected global::System.Web.UI.WebControls.Literal litContent;
        protected global::System.Web.UI.WebControls.HyperLink lnkPrevLesson;
        protected global::System.Web.UI.WebControls.Button btnMarkComplete;
        protected global::System.Web.UI.WebControls.Button btnMarkIncomplete;
        protected global::System.Web.UI.WebControls.HyperLink lnkNextLesson;
        protected global::System.Web.UI.WebControls.HyperLink lnkFinishCourse;
        protected global::System.Web.UI.WebControls.Repeater rptOtherLessons;
    }
}
