// <auto-generated />
namespace Codelecta_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddVideoUrlToLesson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("Codelecta_2._0.Migrations.202608201022420_AddVideoUrlToLesson", typeof(AddVideoUrlToLesson).Assembly);
        
        string IMigrationMetadata.Id
        {
            get { return "202608201022420_AddVideoUrlToLesson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
