//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0.Account
{
    public partial class Manage
    {
        protected global::System.Web.UI.WebControls.Label lblAvatarInitial;
        protected global::System.Web.UI.WebControls.Label lblProfileHeading;
        protected global::System.Web.UI.WebControls.Label lblAccountRole;
        protected global::System.Web.UI.WebControls.Label lblEmailAddress;
        protected global::System.Web.UI.WebControls.Label lblStatCourses;
        protected global::System.Web.UI.WebControls.Label lblStatCertificates;
        protected global::System.Web.UI.WebControls.Panel pnlStatusMessage;
        protected global::System.Web.UI.WebControls.Label lblStatusMessage;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.DropDownList ddlExperienceLevel;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
    }
}
