//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0.Admin {
    
    public partial class ManageLessons {
        
        protected global::System.Web.UI.WebControls.Label lblCourseTitle;
        protected global::System.Web.UI.WebControls.TextBox txtLessonTitle;
        protected global::System.Web.UI.WebControls.TextBox txtLessonContent;
        protected global::System.Web.UI.WebControls.TextBox txtVideoUrl;
        protected global::System.Web.UI.WebControls.TextBox txtOrder;
        protected global::System.Web.UI.WebControls.Button btnAddLesson;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Repeater rptLessons;
        protected global::System.Web.UI.WebControls.Label lblNoLessons;
    }
}
