//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0.Admin
{
    public partial class ManageLessons
    {
        protected global::System.Web.UI.WebControls.Label lblCourseTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlSelectCourse;
        protected global::System.Web.UI.WebControls.Label lblLessonCountHeader;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblActionMessage;
        protected global::System.Web.UI.WebControls.Label lblFormHeading;
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;
        protected global::System.Web.UI.WebControls.HiddenField hfEditingLessonId;
        protected global::System.Web.UI.WebControls.TextBox txtLessonTitle;
        protected global::System.Web.UI.WebControls.TextBox txtOrder;
        protected global::System.Web.UI.WebControls.TextBox txtVideoUrl;
        protected global::System.Web.UI.WebControls.TextBox txtLessonContent;
        protected global::System.Web.UI.WebControls.Button btnSaveLesson;
        protected global::System.Web.UI.WebControls.Label lblTableCount;
        protected global::System.Web.UI.WebControls.Repeater rptLessons;
        protected global::System.Web.UI.WebControls.Panel pnlNoLessons;
    }
}
