//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0.Admin
{
    public partial class ManageEnrollments
    {
        protected global::System.Web.UI.WebControls.Label lblTotalEnrollments;
        protected global::System.Web.UI.WebControls.Label lblCompletedCount;
        protected global::System.Web.UI.WebControls.Label lblInProgressCount;
        protected global::System.Web.UI.WebControls.Label lblUniqueStudents;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblActionMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlUsers;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourses;
        protected global::System.Web.UI.WebControls.Button btnEnrollStudent;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Label lblFilteredCount;
        protected global::System.Web.UI.WebControls.Repeater rptEnrollments;
        protected global::System.Web.UI.WebControls.Panel pnlNoEnrollments;
    }
}
