//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0.Admin
{
    public partial class ManageQuizzes
    {
        protected global::System.Web.UI.WebControls.Label lblTotalQuizzes;
        protected global::System.Web.UI.WebControls.Label lblTotalQuestions;
        protected global::System.Web.UI.WebControls.Label lblTotalAttempts;
        protected global::System.Web.UI.WebControls.Label lblPassRate;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblActionMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourses;
        protected global::System.Web.UI.WebControls.TextBox txtQuizTitle;
        protected global::System.Web.UI.WebControls.TextBox txtQuizDescription;
        protected global::System.Web.UI.WebControls.TextBox txtPassingScore;
        protected global::System.Web.UI.WebControls.Button btnCreateQuiz;
        protected global::System.Web.UI.WebControls.Label lblQuizCount;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
        protected global::System.Web.UI.WebControls.Panel pnlNoQuizzes;
    }
}
