//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelecta_2._0.Admin
{
    public partial class ManageCourses
    {
        protected global::System.Web.UI.WebControls.Label lblTotalCourses;
        protected global::System.Web.UI.WebControls.Label lblTotalLessons;
        protected global::System.Web.UI.WebControls.Label lblTotalEnrollments;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblActionMessage;
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;
        protected global::System.Web.UI.WebControls.HiddenField hfEditingCourseId;
        protected global::System.Web.UI.WebControls.TextBox txtCourseTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourseLevel;
        protected global::System.Web.UI.WebControls.TextBox txtCourseDescription;
        protected global::System.Web.UI.WebControls.TextBox txtImageTag;
        protected global::System.Web.UI.WebControls.DropDownList ddlBadgeClass;
        protected global::System.Web.UI.WebControls.Button btnSaveCourse;
        protected global::System.Web.UI.WebControls.Label lblCourseCount;
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
        protected global::System.Web.UI.WebControls.Panel pnlNoCourses;
    }
}
